version: '3.9'
services:
  voicevox:
    image: voicevox/voicevox_engine:nvidia-0.25.2@sha256:f77258b7239be4ea95537aa5bb4fdffe954bc498ff8125d6da1e97a22024846d
    hostname: voicevox
    container_name: voicevox__voicevox
    restart: unless-stopped

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              # Fix for docker-ce 27.3.x bugs.
              # refs:
              #   https://x.com/yanorei32/status/1840455188928405554
              #   https://github.com/moby/moby/pull/48483
              #   https://docs.docker.com/compose/how-tos/gpu-support/
              count: all
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1-amd64@sha256:d68fa057087c359c79a255570e891215877ce48aa48ba6f28aac90d8077acbc3
    hostname: cloudflared
    container_name: voicevox__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:
      outband:
      prometheus__cloudflared:
        aliases:
          - voicevox__cloudflared

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    external: true

  default:
    name: voicevox__default
    internal: true

  outband:
    name: voicevox__outband
